export const foodList = [
    {name: '麻辣烫', description: ''},
    {name: '盖浇饭', description: ''},
    {name: '炸鸡', description: ''},
    {name: '汉堡', description: ''},
    {name: '黄焖鸡', description: ''},
    {name: '烤肉拌饭', description: ''},
    {name: '寿司', description: ''},
    {name: '奶茶', description: ''},
    {name: '酸辣粉', description: ''},
    {name: '麻辣香锅', description: ''},
    {name: '炒面', description: ''},
    {name: '炒饭', description: ''},
    {name: '炒饼', description: ''},
    {name: '炒年糕', description: ''},
    {name: '凉皮', description: ''},
    {name: '凉面', description: ''},
    {name: '烧烤', description: ''},
    {name: '冒菜', description: ''},
    {name: '鸡公煲', description: ''},
    {name: '钵钵鸡', description: ''},
    {name: '砂锅粥', description: ''},
    {name: '川菜', description: ''},
    {name: '东北菜', description: ''},
    {name: '粤菜', description: ''},
    {name: '食堂', description: ''},
    {name: '螺狮粉', description: ''},
    {name: '披萨', description: ''},
    {name: '热干面', description: ''},
    {name: '小炒肉', description: ''},
    {name: '泡馍', description: ''},
]

export const commonDescription = [
    '先锋模饭作用',
    '一去不复饭',
    '井水不饭河水',
    '饭其道而行之',
    '饭咬一口',
    '饭脸不认人',
    '聪明饭被聪明误',
    '饭事预则立',

    '百吃竿头更进一步',
    '坚吃就是胜利',
    '说时吃那时快',

    '勿以饿小而为之',
    '饿人先告状',
    '癞蛤蟆想吃天饿肉',
    '善饿到头终有报',
    '饿人自有恶人磨',
    '穷山饿水出刁民',

    '一百八食度',
    '理论联系食际',
    '食情况而定',
    '三七二食一',
    '家和万食兴',
    '以迅雷不及掩耳之食',
    '食万八千里',
    '工欲善其食',
]